### ISSUE TITLE
dataset training

### ISSUE THREAD

**Issue by naveensmart395** [AnshulSood11/PPE-Detection-YOLO-Deep_SORT#2]
please help us in trainning the dataset of these helmet

**Comment by naveensmart395** [comment]
please give us your  contact mail id

**Comment by AnshulSood11** [comment]
Please be precise. What help do you need?

**Comment by naveensmart395** [comment]
please help us , how do you train the images person with helmet and
without helmet and where you call the trained file into the predict.py
file

https://github.com/AnshulSood11/PPE-Detection-YOLO-Deep_SORT

**Comment by naveensmart395** [comment]
how to train our custom images ,and how to include in it to your
code????????????

**Comment by AnshulSood11** [comment]
@naveensmart395 did you read ["Training the model"](https://github.com/AnshulSood11/PPE-Detection-YOLO-Deep_SORT#training-the-model) part in README.md? If yes, then what part is not clear to you?

**Comment by naveensmart395** [comment]
we are not clear with that , because we are a beginner to this side ,
please give step by step instructions to train a set of images , our team
totally have no idea  about it
